// lib/preguntas.js
// Reactivos basados en el modelo de Neuroseguridad Laboral (Brain Safety):
// Juicio Situacional (SJT) + Escalas Likert psicofisiológicas.
export const SECCIONES = [
  {
    id: "datos_trabajador",
    titulo: "1. Datos del Trabajador",
    descripcion: "Información básica para ubicar el diagnóstico dentro de la organización.",
    preguntas: [
      { id: "nombre", label: "Nombre completo", type: "text", requerido: true },
      { id: "documento", label: "Número de identificación", type: "text", requerido: true },
      { id: "cargo", label: "Cargo / rol operativo", type: "text", requerido: true },
      { id: "area_planta", label: "Área, planta o frente de trabajo", type: "text", requerido: true },
      { id: "turno", label: "Turno actual", type: "select", options: ["Diurno", "Nocturno", "Rotativo", "Fin de semana"], requerido: true },
      { id: "antiguedad_meses", label: "Antigüedad en el cargo (meses)", type: "number", requerido: false, min: 0, max: 600 },
      { id: "telefono_contacto", label: "Teléfono de contacto", type: "text", requerido: false },
    ],
  },
  {
    id: "percepcion_riesgo",
    titulo: "2. Percepción del Riesgo",
    descripcion: "Qué tanto reconoce el trabajador los peligros presentes en su labor diaria.",
    preguntas: [
      { id: "riesgo_normalizacion", label: "¿Con qué frecuencia siente que 'ya se acostumbró' a un peligro de su labor y dejó de prestarle atención?", type: "select", options: ["Nunca", "Rara vez", "A veces", "Frecuentemente", "Siempre"], peso: [0,1,2,3,4], requerido: true },
      { id: "riesgo_evaluacion_previa", label: "Antes de iniciar una tarea de riesgo, ¿evalúa conscientemente los peligros presentes?", type: "select", options: ["Siempre", "Casi siempre", "A veces", "Rara vez", "Nunca"], peso: [0,1,2,3,4], requerido: true },
      { id: "riesgo_senales_alerta", label: "¿Qué tan seguido nota señales de alerta (ruidos, olores, vibraciones anómalas) que otros no perciben?", type: "select", options: ["Muy frecuente", "Frecuente", "Ocasional", "Rara vez", "Nunca"], peso: [0,1,2,3,4], requerido: true },
      { id: "riesgo_confianza_excesiva", label: "¿Ha sentido que por la experiencia acumulada, ciertos pasos de seguridad 'ya no le hacen falta'?", type: "select", options: ["Nunca", "Rara vez", "A veces", "Frecuentemente", "Siempre"], peso: [0,1,2,3,4], requerido: true },
      { id: "riesgo_reporte_condiciones", label: "Cuando detecta una condición insegura, ¿la reporta de inmediato?", type: "select", options: ["Siempre", "Casi siempre", "A veces", "Rara vez", "Nunca"], peso: [0,1,2,3,4], requerido: true },
      { id: "riesgo_percepcion_propia_vulnerabilidad", label: "¿Considera que a usted específicamente 'no le puede pasar' un accidente grave?", type: "select", options: ["Totalmente en desacuerdo", "En desacuerdo", "Neutral", "De acuerdo", "Totalmente de acuerdo"], peso: [0,1,2,3,4], requerido: true },
      { id: "riesgo_zonas_criticas", label: "¿Identifica con claridad cuáles son las zonas o tareas de mayor riesgo en su área?", type: "select", options: ["Sí, con total claridad", "En su mayoría sí", "Parcialmente", "Con dificultad", "No las identifica"], peso: [0,1,2,3,4], requerido: true },
      { id: "riesgo_ultima_semana_cerca", label: "En la última semana, ¿estuvo cerca de cometer un error que pudo haber causado un incidente?", type: "select", options: ["Sí", "No", "No estoy seguro"], peso: [2,0,1], requerido: true },
    ],
  },
  {
    id: "fatiga_carga_mental",
    titulo: "3. Fatiga y Carga Mental",
    descripcion: "Acumulación de cansancio, deuda de sueño y carga cognitiva durante la jornada.",
    preguntas: [
      { id: "fatiga_maniobra_automatica", label: "¿En cuántas ocasiones durante la última semana sintió que ejecutó una maniobra de forma automática, sin recordar el procedimiento exacto?", type: "select", options: ["Ninguna", "1 a 2 veces", "3 a 5 veces", "Más de 5 veces"], peso: [0,1,2,3], requerido: true },
      { id: "fatiga_horas_sueno_ultima_noche", label: "¿Cuántas horas durmió la noche anterior a este diagnóstico?", type: "number", requerido: true, min: 0, max: 24 },
      { id: "fatiga_horas_sueno_promedio_semana", label: "¿Cuál es su promedio de horas de sueño en la última semana?", type: "number", requerido: true, min: 0, max: 24 },
      { id: "fatiga_somnolencia_turno", label: "Durante su turno, ¿siente somnolencia o pesadez para mantenerse despierto?", type: "select", options: ["Nunca", "Rara vez", "A veces", "Frecuentemente", "Constantemente"], peso: [0,1,2,3,4], requerido: true },
      { id: "fatiga_concentracion_final_turno", label: "Hacia el final del turno, ¿su capacidad de concentración disminuye notablemente?", type: "select", options: ["Nada", "Poco", "Moderadamente", "Bastante", "Mucho"], peso: [0,1,2,3,4], requerido: true },
      { id: "fatiga_carga_mental_percibida", label: "¿Qué tan mentalmente exigente considera su turno actual?", type: "select", options: ["Muy baja", "Baja", "Moderada", "Alta", "Muy alta"], peso: [0,1,2,3,4], requerido: true },
      { id: "fatiga_recuperacion_pausas", label: "¿Las pausas o descansos asignados son suficientes para recuperarse durante la jornada?", type: "select", options: ["Totalmente suficientes", "Suficientes", "Parcialmente suficientes", "Insuficientes", "Nulas o no las toma"], peso: [0,1,2,3,4], requerido: true },
      { id: "fatiga_sintomas_fisicos", label: "¿Presenta síntomas físicos asociados al cansancio (dolor de cabeza, tensión muscular, ojos irritados)?", type: "select", options: ["Nunca", "Rara vez", "A veces", "Frecuentemente", "Siempre"], peso: [0,1,2,3,4], requerido: true },
      { id: "fatiga_dias_libres_recientes", label: "¿Cuántos días de descanso completo ha tenido en los últimos 7 días?", type: "number", requerido: true, min: 0, max: 7 },
    ],
  },
  {
    id: "tolerancia_impulsividad",
    titulo: "4. Tolerancia a la Impulsividad",
    descripcion: "Disposición a omitir protocolos, EPP o reglas bajo presión.",
    preguntas: [
      { id: "impulsividad_omitir_epp_prisa", label: "¿Alguna vez ha omitido algún elemento de protección personal (EPP) por estar de prisa?", type: "select", options: ["Nunca", "Rara vez", "A veces", "Frecuentemente"], peso: [0,1,2,3], requerido: true },
      { id: "impulsividad_atajos_procedimiento", label: "¿Con qué frecuencia toma 'atajos' respecto al procedimiento formal para ganar tiempo?", type: "select", options: ["Nunca", "Rara vez", "A veces", "Frecuentemente", "Siempre"], peso: [0,1,2,3,4], requerido: true },
      { id: "impulsividad_presion_supervisor", label: "Cuando un supervisor presiona por tiempo, ¿le cuesta mantener el procedimiento completo?", type: "select", options: ["Nunca", "Rara vez", "A veces", "Frecuentemente", "Siempre"], peso: [0,1,2,3,4], requerido: true },
      { id: "impulsividad_decision_bajo_presion", label: "Ante una decisión de seguridad bajo presión de tiempo, ¿tiende a actuar antes de terminar de evaluar el riesgo?", type: "select", options: ["Nunca", "Rara vez", "A veces", "Frecuentemente", "Siempre"], peso: [0,1,2,3,4], requerido: true },
      { id: "impulsividad_senala_error_companero", label: "Si ve a un compañero saltarse un paso de seguridad, ¿se lo hace notar en el momento?", type: "select", options: ["Siempre", "Casi siempre", "A veces", "Rara vez", "Nunca"], peso: [0,1,2,3,4], requerido: true },
      { id: "impulsividad_espera_antes_actuar", label: "¿Le resulta difícil esperar el tiempo necesario (bloqueo, verificación, permiso) antes de intervenir un equipo?", type: "select", options: ["Nunca", "Rara vez", "A veces", "Frecuentemente", "Siempre"], peso: [0,1,2,3,4], requerido: true },
      { id: "impulsividad_meta_produccion", label: "¿Ha sentido que las metas de producción compiten directamente con seguir el protocolo de seguridad?", type: "select", options: ["Nunca", "Rara vez", "A veces", "Frecuentemente", "Siempre"], peso: [0,1,2,3,4], requerido: true },
      { id: "impulsividad_reaccion_imprevisto", label: "Ante un imprevisto repentino en su tarea, ¿su primera reacción suele ser actuar de inmediato antes de detenerse a pensar?", type: "select", options: ["Nunca", "Rara vez", "A veces", "Frecuentemente", "Siempre"], peso: [0,1,2,3,4], requerido: true },
    ],
  },
  {
    id: "clima_seguridad",
    titulo: "5. Clima de Seguridad",
    descripcion: "Percepción del entorno organizacional respecto a la seguridad.",
    preguntas: [
      { id: "clima_apoyo_reportar", label: "¿Siente que puede reportar un riesgo o error sin temor a represalias?", type: "select", options: ["Totalmente de acuerdo", "De acuerdo", "Neutral", "En desacuerdo", "Totalmente en desacuerdo"], peso: [0,1,2,3,4], requerido: true },
      { id: "clima_liderazgo_ejemplo", label: "¿Sus líderes directos dan ejemplo cumpliendo las normas de seguridad?", type: "select", options: ["Siempre", "Casi siempre", "A veces", "Rara vez", "Nunca"], peso: [0,1,2,3,4], requerido: true },
      { id: "clima_presion_metas", label: "¿Qué tan presionado se siente por cumplir metas de producción o tiempos?", type: "select", options: ["Nada presionado", "Poco presionado", "Moderadamente presionado", "Muy presionado", "Extremadamente presionado"], peso: [0,1,2,3,4], requerido: true },
      { id: "clima_recursos_disponibles", label: "¿Cuenta con los recursos y EPP necesarios en buen estado para realizar su labor de forma segura?", type: "select", options: ["Siempre", "Casi siempre", "A veces", "Rara vez", "Nunca"], peso: [0,1,2,3,4], requerido: true },
      { id: "clima_comunicacion_cambios", label: "¿Se le comunican con claridad los cambios en procedimientos de seguridad?", type: "select", options: ["Siempre", "Casi siempre", "A veces", "Rara vez", "Nunca"], peso: [0,1,2,3,4], requerido: true },
      { id: "clima_participacion_decisiones", label: "¿Siente que su opinión sobre riesgos operativos es tenida en cuenta?", type: "select", options: ["Siempre", "Casi siempre", "A veces", "Rara vez", "Nunca"], peso: [0,1,2,3,4], requerido: true },
      { id: "clima_capacitacion_reciente", label: "¿Ha recibido capacitación en seguridad en los últimos 3 meses?", type: "select", options: ["Sí", "No", "No recuerda"], peso: [0,2,1], requerido: true },
      { id: "clima_confianza_equipo", label: "¿Confía en que sus compañeros de turno seguirán los protocolos de seguridad?", type: "select", options: ["Totalmente", "Bastante", "Moderadamente", "Poco", "Nada"], peso: [0,1,2,3,4], requerido: true },
    ],
  },
  {
    id: "juicio_situacional",
    titulo: "6. Juicio Situacional",
    descripcion: "Escenarios reales de operación. Elija la opción que más se acerque a lo que usted haría.",
    preguntas: [
      { id: "sjt_valvula_cierre_turno", label: "Faltan 10 minutos para cerrar el turno y nota una anomalía menor en una válvula de alta presión. Su supervisor pide liberar la línea ya. ¿Qué hace?", type: "select", options: ["Detengo la operación y reporto la anomalía antes de continuar", "Libero la línea pero aviso que quedó pendiente revisión", "Libero la línea como se pidió, confiando en que no es grave", "Le pido a otro compañero que decida por mí"], peso: [0,1,2,3], requerido: true },
      { id: "sjt_epp_incompleto_urgencia", label: "Debe atender una falla urgente y su EPP completo está en otra área a 5 minutos. ¿Qué hace?", type: "select", options: ["Voy por el EPP completo aunque implique demorar la atención", "Empiezo con el EPP que tengo a mano y complemento después", "Atiendo la falla sin EPP completo por la urgencia", "Delego la tarea a otra persona que sí tenga el EPP"], peso: [0,1,2,3], requerido: true },
      { id: "sjt_companero_sin_bloqueo", label: "Ve a un compañero a punto de intervenir un equipo sin aplicar el bloqueo y etiquetado (LOTO). ¿Qué hace?", type: "select", options: ["Lo detengo de inmediato y exijo el bloqueo antes de continuar", "Le aviso pero sigo con lo mío", "Asumo que él sabe lo que hace y no digo nada", "Reporto después del hecho, sin intervenir en el momento"], peso: [0,1,2,3], requerido: true },
      { id: "sjt_fatiga_turno_extra", label: "Le ofrecen un turno extra tras 10 horas ya trabajadas y se siente agotado. ¿Qué hace?", type: "select", options: ["Rechazo el turno extra y comunico el motivo", "Acepto pero pido una pausa antes de iniciar", "Acepto sin decir nada sobre mi cansancio", "Acepto y le resto importancia al cansancio"], peso: [0,1,2,3], requerido: true },
      { id: "sjt_alarma_intermitente", label: "Una alarma de proceso suena de forma intermitente hace días sin causa clara identificada. ¿Qué hace?", type: "select", options: ["Escalo el reporte formalmente hasta que se investigue a fondo", "Sigo trabajando y la reporto solo si empeora", "Me acostumbro al sonido y continúo normalmente", "Apago o silencio la alarma para concentrarme en la tarea"], peso: [0,1,2,3], requerido: true },
      { id: "sjt_procedimiento_desactualizado", label: "Nota que el procedimiento escrito no coincide con la forma en que realmente se hace la tarea en planta. ¿Qué hace?", type: "select", options: ["Reporto la inconsistencia para que se actualice el procedimiento", "Sigo la forma real (la práctica) sin reportar nada", "Sigo el procedimiento escrito aunque no coincida con la práctica", "Pregunto a un compañero cuál seguir, sin escalarlo"], peso: [0,1,2,3], requerido: true },
      { id: "sjt_clima_extremo", label: "Debe realizar trabajo en altura y las condiciones climáticas están en el límite de lo permitido. ¿Qué hace?", type: "select", options: ["Suspendo la actividad hasta que las condiciones mejoren", "Continúo con precauciones adicionales por mi cuenta", "Continúo normalmente porque ya lo he hecho antes en condiciones similares", "Pido a un compañero con más experiencia que decida"], peso: [0,1,2,3], requerido: true },
      { id: "sjt_error_propio_no_visto", label: "Comete un error operativo que nadie más notó y no generó consecuencias visibles. ¿Qué hace?", type: "select", options: ["Lo reporto igual, porque pudo haber generado un riesgo", "Lo corrijo pero no lo reporto formalmente", "No hago nada, ya que no tuvo consecuencias", "Se lo comento solo a un compañero de confianza"], peso: [0,1,2,3], requerido: true },
      { id: "sjt_espacio_confinado_permiso", label: "Debe ingresar a un espacio confinado y el permiso de trabajo aún no está firmado por completo. ¿Qué hace?", type: "select", options: ["Espero a que el permiso esté completamente firmado antes de ingresar", "Ingreso y regularizo el permiso después", "Ingreso solo unos minutos mientras completan el permiso", "Pido a otra persona que ingrese primero"], peso: [0,1,2,3], requerido: true },
      { id: "sjt_reporte_falso_positivo", label: "Reportó una condición insegura y, tras la revisión, resultó no ser grave. Un compañero se burla por el reporte. ¿Cómo reacciona?", type: "select", options: ["Mantengo mi postura: prefiero reportar aunque a veces no sea grave", "Me siento incómodo y probablemente reporte menos en el futuro", "Le resto importancia y sigo reportando igual que antes", "Evito comentar el tema y minimizo lo ocurrido"], peso: [0,1,2,3], requerido: true },
    ],
  },
  {
    id: "habitos_autopercepcion",
    titulo: "7. Hábitos y Autopercepción",
    descripcion: "Factores de estilo de vida que inciden en el estado neuroconductual durante la operación.",
    preguntas: [
      { id: "habitos_consumo_cafeina", label: "¿Cuántas bebidas con cafeína consume durante su turno?", type: "select", options: ["Ninguna", "1", "2 a 3", "Más de 3"], peso: [0,1,2,3], requerido: true },
      { id: "habitos_actividad_fisica", label: "¿Con qué frecuencia realiza actividad física fuera del trabajo?", type: "select", options: ["Nunca", "Ocasionalmente", "1 a 2 veces por semana", "3 o más veces por semana"], requerido: false },
      { id: "habitos_alimentacion_turno", label: "¿Logra alimentarse adecuadamente durante su turno?", type: "select", options: ["Siempre", "Casi siempre", "A veces", "Rara vez", "Nunca"], peso: [0,1,2,3,4], requerido: true },
      { id: "habitos_uso_celular_operacion", label: "¿Con qué frecuencia usa el celular mientras realiza tareas operativas?", type: "select", options: ["Nunca", "Rara vez", "A veces", "Frecuentemente"], peso: [0,1,2,3], requerido: true },
      { id: "habitos_situacion_personal_afecta", label: "¿Alguna situación personal reciente le está costando trabajo dejar de pensar durante su turno?", type: "select", options: ["No", "Un poco", "Moderadamente", "Bastante"], peso: [0,1,2,3], requerido: false },
      { id: "habitos_percepcion_propio_estado", label: "En general, ¿cómo calificaría su estado de alerta en este momento?", type: "select", options: ["Muy alerta", "Alerta", "Neutral", "Algo disperso", "Muy disperso"], peso: [0,1,2,3,4], requerido: true },
      { id: "habitos_rotacion_turnos_afecta", label: "¿La rotación de turnos afecta notablemente su descanso y concentración?", type: "select", options: ["Nada", "Poco", "Moderadamente", "Bastante", "Mucho"], peso: [0,1,2,3,4], requerido: true },
      { id: "habitos_evento_previo_turno", label: "¿Tuvo algún evento significativo antes de iniciar este turno que le haya cambiado el ánimo?", type: "select", options: ["No", "Sí, positivo", "Sí, negativo o estresante"], peso: [0,0,2], requerido: false },
      { id: "habitos_disposicion_reportar_fatiga", label: "Si se sintiera demasiado fatigado para trabajar con seguridad, ¿se lo comunicaría a su supervisor?", type: "select", options: ["Sí, sin dudarlo", "Probablemente sí", "No estoy seguro", "Probablemente no", "No, nunca"], peso: [0,1,2,3,4], requerido: true },
      { id: "habitos_observaciones", label: "¿Algo más que quiera comunicar sobre su estado antes de iniciar la operación?", type: "textarea", requerido: false },
    ],
  },
];